#ifndef GUI_ART_H
#define GUI_ART_H

#include <cstdint>

#include "gl.h"

// Generated by tools/gen_gui_art.py (original art). Transparent key: 0xF81F.

// The pixel font: ASCII 32-126, 9 rows (0-6 cap height, 7-8 descenders),
// up to 5 columns per row, bit 4 = leftmost column.
extern const uint8_t gui_font_widths[95];
extern const uint8_t gui_font_rows[95][9];

// 9x9 HUD cells in a row: heart full, half, empty; hunger full, half, empty;
// air bubble, popping bubble.
extern TEXTURE gui_hud;
enum HudIcon { HUD_HEART = 0, HUD_HEART_HALF, HUD_HEART_EMPTY, HUD_FOOD, HUD_FOOD_HALF, HUD_FOOD_EMPTY, HUD_BUBBLE, HUD_BUBBLE_POP };

// Ten 16x16 block-breaking stages in a row.
extern TEXTURE gui_crack;

// The "CRAFTI" wordmark for the menu.
extern TEXTURE gui_title;

#endif // GUI_ART_H
