#ifndef ITEM_ICONS_H
#define ITEM_ICONS_H

#include "gl.h"
#include "items.h"

// Generated by tools/gen_item_icons.py (original art).
const TEXTURE &itemIconAtlas();

// The 16x16 cell for an item. Returns false for IDs without an icon.
bool itemIconUV(ItemId id, int &u, int &v);

#endif // ITEM_ICONS_H
